<?php
/**
 * Created by PhpStorm.
 * User: MarekHvolka
 * Date: 15.05.16
 * Time: 1:13
 */

namespace backend\components\BlockModal;

class AssetBundle extends \yii\web\AssetBundle
{
    public $css = [
        'css/style.css'
    ];

    public $js = [
        'js/modal.js'
    ];

    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        //'kartik\select2\Select2',
        //'kartik\switchinput\SwitchInput'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = __DIR__ . "/assets";
    }

}