<?php
/**
 * Created by PhpStorm.
 * User: MarekHvolka
 * Date: 15.05.16
 * Time: 1:13
 */

namespace backend\components\BlockModal;

class AssetBundle extends \yii\web\AssetBundle
{
  //  public $basePath = '@app/components/BlockModal/assets';

    public $css = [
        'css/style.css'
    ];

    public $js = [
        'js/modal.js'
    ];

    public $depends = [
        'backend\assets\CKEditorAsset',
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = __DIR__ . "/assets";
    }

}