<?php

namespace backend\controllers;

use backend\components\GlobalSearchWidget;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;

/**
 * DictionaryController implements the CRUD actions for Dictionary model.
 */
abstract class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->view->params['globalSearchModel'] = new GlobalSearchWidget();

        $this->view->params['menuItems'] = [
            ['label' => '<i class="fa fa-fw fa-files-o"></i> Stránky', 'url' => ['/page/index']],
            ['label' => '<i class="fa fa-fw fa-code"></i> Kódy', 'url' => ['/tracking-code/index']],
            ['label' => '<i class="fa fa-fw fa-globe"></i> Globálne nastavenia', 'url' => ['/page/index']],
            '<li class="menu_line" ><a href="javascript: void(0);" data-toggle="collapse" data-target="#Menu"><i class="fa fa-fw fa-"></i>  </a></li>',
            ['label' => '<i class="fa fa-fw fa-thumbs-o-up"></i> Ďakovačky', 'url' => ['/page/index']],
            ['label' => '<i class="fa fa-fw fa-picture-o"></i> Multimédiá', 'url' => ['/multimedia/index']],
            ['label' => '<i class="fa fa-fw fa-book"></i> Slovník', 'url' => ['/dictionary/index']],
            ['label' => '<i class="fa fa-fw fa-puzzle-piece"></i> Snippety', 'url' => ['/snippet/index']],
            ['label' => '<i class="fa fa-fw fa-shopping-cart"></i> Produkty',
                'items' => [
                    ['label' => 'Zoznam produktov', 'url' => ['/product/index']],
                    ['label' => 'Zoznam vlastností', 'url' => ['/product-var/index']],
                    ['label' => 'Zoznam typov', 'url' => ['/product-type/index']],
                    ['label' => 'Zoznam tagov', 'url' => ['/tag/index']],
                ],],
            ['label' => '<i class="fa fa-fw fa-paint-brush"></i> Šablóny', 'url' => ['/template/index']],
            ['label' => '<i class="fa fa-fw fa-cogs"></i> Nastavenia',
                'items' => [
                    ['label' => 'Administrácia používateľov', 'url' => ['/user/index']],
                    ['label' => 'Administrácia portálov', 'url' => ['/portal/index']],
                    ['label' => 'Administrácia premenných portálov', 'url' => ['/portal-var/index']],
                    ['label' => 'Administrácia krajín', 'url' => ['/language/index']],
                    ['label' => 'Administrácia rolí', 'url' => ['/role/index']],
                    ['label' => 'Administrácia oprávnení', 'url' => ['/portal/index']],
                ],],
        ];

        $this->view->params['menuItems'] =
            [
                ['label' => '<i class="fa fa-fw fa-files-o"></i> Stránky', 'url' => Url::to(['/page/index'])],
                ['label' => '<i class="fa fa-fw fa-globe"></i> Globálne nastavenia',
                    'items' => [
                        ['label' => 'Globálna hlavička', 'url' => Url::to(['/product/index'])],
                        ['label' => 'Globálna pätička', 'url' => Url::to(['/product-var/index'])],
                        ['label' => 'Meracie kódy', 'url' => Url::to(['/tracking-code/index'])],
                    ],
                ],
                ['label' => '<i class="fa fa-fw fa-thumbs-o-up"></i> Ďakovačky', 'url' => Url::to(['/tracking-code/index'])],
                ['label' => '<i class="fa fa-fw fa-picture-o"></i> Multimédiá', 'url' => Url::to(['/tracking-code/index'])],
                ['label' => '<i class="fa fa-fw fa-book"></i> Slovník', 'url' => Url::to(['/dictionary/index'])],
                ['label' => '<i class="fa fa-fw fa-puzzle-piece"></i> Snippety', 'url' => Url::to(['/snippet/index'])],
                ['label' => '<i class="fa fa-fw fa-shopping-cart"></i> Produkty',
                    'items' => [
                        ['label' => 'Zoznam produktov', 'url' => Url::to(['/product/index'])],
                        ['label' => 'Zoznam premenných', 'url' => Url::to(['/product-var/index'])],
                        ['label' => 'Zoznam typov', 'url' => Url::to(['/product-type/index'])],
                        ['label' => 'Zoznam tagov', 'url' => Url::to(['/tag/index'])],
                    ],
                ],
                ['label' => '<i class="fa fa-fw fa-paint-brush"></i> Šablóny', 'url' => Url::to(['/template/index'])],
                ['label' => '<i class="fa fa-fw fa-cogs"></i> Nastavenia',
                    'items' => [
                        ['label' => 'Administrácia portálov', 'url' => Url::to(['/portal/index'])],
                        ['label' => 'Administrácia používateľov', 'url' => Url::to(['/user/index'])],
                        ['label' => 'Portálové premenné', 'url' => Url::to(['/portal-var/index'])],
                        ['label' => 'Administrácia krajín', 'url' => Url::to(['/language/index'])],
                        ['label' => 'Administrácia rolí', 'url' => Url::to(['/product-type/index'])],
                        ['label' => 'Administrácia oprávnení', 'url' => Url::to(['/tag/index'])],
                    ],
                ],
                ['label' => '<i class="fa fa-fw fa-thumbs-o-up"></i> Sections', 'url' => Url::to(['/tracking-code/index'])],
            ];
    }
}
