<?php

namespace backend\components\MultipleSwitch;

class MultipleSwitchAsset extends \yii\web\AssetBundle
{
    public $js = [
        'js/multiple-switch.js'
    ];

    public $depends = [
        'backend\assets\AppAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = __DIR__ . "/assets";
    }
}