<?php
/**
 * Created by PhpStorm.
 * User: MarekHvolka
 * Date: 15.05.16
 * Time: 1:13
 */

namespace backend\components\MultimediaWidget;


use yii\web\AssetBundle;

class MultimediaWidgetAsset extends AssetBundle
{
    public $css = [
        'css/style.css'
    ];

    public $js = [
        'js/multimedia.js'
    ];

    public $depends = [
        'backend\assets\FancyBoxAsset',
        'yii\web\JqueryAsset',
        'backend\assets\BlockModal\AssetBundle'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = __DIR__ . "/web";
    }
}