<?php

namespace backend\components\ToggleSwitch;

class ToggleSwitchAsset extends \yii\web\AssetBundle
{
    public $css = [
        'https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css'
    ];

    public $js = [
        'https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js',
        'js/toggle-switch.js'
    ];

    public $depends = [
        'backend\assets\AppAsset',

    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = __DIR__ . "/assets";
    }
}