<?php

namespace backend\models;

use common\models\User;
use Yii;
use yii\base\Exception;

/**
 * Model reprezentujúci podstránku portálu.
 *
 * @property integer $id
 * @property string $name
 * @property string $identifier
 * @property integer $portal_id
 * @property integer $active
 * @property integer $parent_id
 * @property integer $product_id
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property string $color_scheme
 * @property string $sidebar_side
 * @property string $last_edit
 * @property integer $last_edit_user
 * @property string $breadcrumbs
 * @property bool $outdated
 * @property bool $head_outdated
 *
 * @property Portal $portal
 * @property User $lastEditUser
 * @property Page $parent
 * @property Page[] $pages
 * @property Section[] $sections
 * @property Product $product
 * @property SnippetVarValue[] $snippetVarValues
 * @property Area $header
 * @property Area $footer
 * @property Area $content
 * @property Area $sidebar
 *
 * @property string $cacheIdentifier
 */
class Page extends LayoutOwner implements ICacheable, IDuplicable
{
    #region BASIC MODEL

    /**
     * @inheritdoc
     */
    public static function tableName() { return 'page'; }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'name',
                    'identifier',
                    'portal_id',
                    'active',
                    'color_scheme',
                    'sidebar_side',
                ],
                'required'
            ],
            [
                [
                    'portal_id',
                    'active',
                    'parent_id',
                    'product_id',
                    'last_edit_user'
                ],
                'integer'
            ],
            [['description', 'keywords'], 'string'],
            [['last_edit', 'breadcrumbs', 'url'], 'safe'],
            [['name', 'identifier', 'color_scheme'], 'string', 'max' => 80],
            [['title'], 'string', 'max' => 150],
            [
                ['identifier', 'portal_id', 'parent_id'],
                'unique',
                'targetAttribute' => ['identifier', 'portal_id', 'parent_id'],
                'message' => 'The combination of Identifier, Portal ID and Parent ID has already been taken.'
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Meno',
            'identifier' => 'Identifikátor',
            'url' => 'Url',
            'portal_id' => 'Portál',
            'active' => 'Aktívna',
            'parent_id' => 'Predok',
            'product_id' => 'Produkt',
            'title' => 'Titulok',
            'description' => 'Popis',
            'keywords' => 'Kľúčové slová',
            'color_scheme' => 'Farebná schéma',
            'sidebar_side' => 'Pozícia sidebaru',
            'last_edit' => 'Posledná zmena',
            'last_edit_user' => 'Naposledy editoval'
        ];
    }

    #endregion

    #region GETTERS & SETTERS

    /** Metoda na vyskladanie URL pre podstranku
     * @return string
     */
    public function getUrl()
    {
        if ($this->identifier == 'homepage' && !$this->parent) {
            return '/';
        }

        $url = isset($this->parent) ? $this->parent->url : '/';

        return $url . $this->identifier . '/';
    }

    /** Metoda na vyskladanie URL pre podstranku
     * @return string
     */
    public function getBreadcrumbs()
    {
        return (isset($this->parent) ? $this->parent->breadcrumbs . ' -> ' : '') . $this->name;
    }

    /** Metoda vrati identifikator pre potreby cache
     * @return string
     */
    public function getCacheIdentifier() { return '$page' . $this->id; }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        $product = $this->hasOne(Product::className(), ['id' => 'product_id']);

        if (!$product->exists() && (isset($this->parent))) {
            return $this->parent->product;
        }
        return $product;
    }

    #region AUTOGENERATED

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPortal()
    {
        return $this->hasOne(Portal::className(), ['id' => 'portal_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Page::className(), ['id' => 'parent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPages()
    {
        return $this->hasMany(Page::className(), ['parent_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSections()
    {
        return $this->hasMany(Section::className(), ['page_id' => 'id']);
    }

    public function getSnippetVarValues()
    {
        return $this->hasMany(SnippetVarValue::className(), ['value_page_id' => 'id']);
    }

    #endregion

    #endregion

    #region CACHING

    /** Vrati cestu k suboru, v ktorom su ulozene premenne podstranky (hlavicka)
     * @return string
     */
    public function getVarCacheFile()
    {
        $path = $this->getMainDirectory() . 'page_var.php';

        if (!file_exists($path) || $this->outdated || $this->head_outdated) {
            try {
                $dataEngine = Yii::$app->dataEngine;

                $buffer = '<?php ' . PHP_EOL;

                if (isset($this->parent)) {
                    $buffer .= 'include("' . $this->parent->getVarCacheFile() . '");' . PHP_EOL;
                }

                if (isset($this->product)) {
                    $buffer .= '$product = $' . $this->product->identifier . ';' . PHP_EOL;
                } else if (isset($this->parent)) {
                    $buffer .= '$product = $portal->pages->page' . $this->parent->id . '->product' . ';' . PHP_EOL;
                } else {
                    $buffer .= '$emptyProduct = (object) array();' . PHP_EOL;
                    $buffer .= '$product = new ObjectBridge($emptyProduct, \'\');' . PHP_EOL;
                }
                $buffer .= '$tempObject = (object) array(' . PHP_EOL;

                $buffer .= '\'id\' => ' . $this->id . ',' . PHP_EOL;
                $buffer .= '\'url\' => \'' . $dataEngine->normalizeString($this->url) . '\',' . PHP_EOL;
                $buffer .= '\'name\' => \'' . $dataEngine->normalizeString($this->name) . '\',' . PHP_EOL;
                $buffer .= '\'title\' => \'' . $dataEngine->normalizeString($this->title) . '\',' . PHP_EOL;
                $buffer .= '\'description\' => \'' . $dataEngine->normalizeString($this->description) . '\',' . PHP_EOL;
                $buffer .= '\'keywords\' => \'' . $dataEngine->normalizeString($this->keywords) . '\',' . PHP_EOL;
                $buffer .= '\'active\' => ' . $this->active . ',' . PHP_EOL;

                if (isset($this->product)) {
                    $buffer .= '\'product\' => $product,' . PHP_EOL;
                }

                $buffer .= ');' . PHP_EOL;

                if ($this->parent) {
                    $buffer .= '$tempObject->parent = ' . $this->parent->cacheIdentifier . ';' . PHP_EOL;

                    $buffer .= '$tempObject->parents = array_merge_recursive($tempObject->parent->parents,
                    array($tempObject->parent));' . PHP_EOL;
                } else {
                    $buffer .= '$tempObject->parents = array();' . PHP_EOL;
                }

                $buffer .= $this->cacheIdentifier . ' = new ObjectBridge($tempObject, \'page' . $this->id . '\');' . PHP_EOL;

                $buffer .= '$page = ' . $this->cacheIdentifier . ';' . PHP_EOL;

                $buffer .= '?>';

                $dataEngine->writeToFile($path, 'w+', $buffer);
                $this->head_outdated = 0;
                $this->save();
                $this->removeException();
            } catch (Exception $exception) {
                $this->logException($exception, 'page_var');
            }
        }

        return $path;
    }

    /** Metoda, resetujuca cache podstranky po zmene
     * @param string $type
     */
    public function resetAfterUpdate($type = 'all')
    {
        $this->setOutdated();

        if ($this->isChanged() && $this->isHeadChanged()) {
            foreach ($this->pages as $page) {
                $page->resetAfterUpdate();
            }

            foreach ($this->snippetVarValues as $snippetVarValue) {
                $snippetVarValue->resetAfterUpdate();
            }
        }
    }

    /** Metoda, vracajuca, ci sa zmenila hlavicka stranky (ktora ovplyvnuje aj ine stranky - menu a podobne)
     * @return bool
     */
    public function isHeadChanged()
    {
        if ($this->myOldAttributes['name'] != $this->name) {
            return true;
        }
        if ($this->myOldAttributes['identifier'] != $this->identifier) {
            return true;
        }
        if ($this->myOldAttributes['product_id'] != $this->product_id) {
            return true;
        }

        return false;
    }

    /** Metoda, ktora vrati, ci bola podstranka zmenena (a je potrebne ju nanovo nacachovat)
     * @return bool
     */
    public function isOutdated()
    {
        return $this->outdated || ($this->product && $this->product->outdated) ||
        $this->portal->outdated || ($this->parent && $this->parent->head_outdated);
    }

    #endregion
}
