<?php

namespace backend\models;

use backend\controllers\BaseController;
use Yii;

/**
 * This is the model class for table "redirect".
 *
 * @property integer $id
 * @property string $source_url
 * @property string $target_url
 * @property integer $redirect_type
 * @property bool $active
 * @property int $last_edit_user
 * @property string $last_edit
 * @property int $portal_id
 * @property Portal $portal
 */
class Redirect extends CustomModel
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->redirect_type = 301;
        $this->active = 1;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'redirect';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['source_url', 'target_url', 'redirect_type', 'portal_id'], 'required'],
            [['source_url', 'target_url'], 'string'],
            [['redirect_type'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'source_url' => 'Zdrojová url',
            'target_url' => 'Cieľová Url',
            'redirect_type' => 'Typ',
            'active' => 'Aktívne',
            'last_edit' => 'Posledná zmena',
            'last_edit_user' => 'Naposledy editoval',
            'portal_id' => 'Portál'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPortal()
    {
        return $this->hasOne(Portal::className(), ['id' => 'portal_id']);
    }
}
