<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "redirect".
 *
 * @property integer $id
 * @property string $source_url
 * @property string $target_url
 * @property integer $redirect_type
 * @property bool $active
 */
class Redirect extends \yii\db\ActiveRecord
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->redirect_type = 301;
        $this->active = 1;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'redirect';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['source_url', 'target_url', 'redirect_type'], 'required'],
            [['source_url', 'target_url'], 'string'],
            [['redirect_type'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'source_url' => 'Zdrojová url',
            'target_url' => 'Cieľová Url',
            'redirect_type' => 'Typ presmerovania',
            'active' => 'Aktívne',
            'last_edit' => 'Posledná zmena',
            'last_edit_user' => 'Naposledy editoval'
        ];
    }
}
